matrix:
  include:
    - os: linux
      language: generic
      env: PYTHON_VERSION=3.6
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6

before_install:
  - ./.travis/install_conda.sh
script:
  - PATH="$HOME/miniconda/bin:$PATH" pytest -v tests/
